import { useState } from "react";
import { toast } from "react-toastify";
import Button from "@/components/ui/Button";
import ExampleButton from "@/components/ui/ExampleButton";
import { wordleGenerator } from "@/lib/puzzles/wordle/generator";
import { usePuzzleStore } from "@/store/puzzle-store";

export default function WordleInput() {
  const { setWordleResult, setWordleTitle } = usePuzzleStore(); const [title, setTitle] = useState(""); const [entries, setEntries] = useState("");
  const generate = () => { const words = entries.split(/\r?\n/).filter((line) => line.trim()).map((line) => { const [word, ...clue] = line.split(":"); return { word: word?.trim() ?? "", clue: clue.join(":").trim() || undefined }; }); try { const result = wordleGenerator.generate({ words }); setWordleResult(result.grid); setWordleTitle(title.trim()); toast.success(`${result.grid.words.length} palabra${result.grid.words.length === 1 ? "" : "s"} generada${result.grid.words.length === 1 ? "" : "s"}`); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo generar el juego"); } };
  return <section className="space-y-5 rounded-xl border border-gray-200 bg-white p-4 sm:p-6" aria-labelledby="wordle-config-title"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="wordle-config-title" className="text-lg font-semibold text-gray-900">Configuración del juego</h2><p className="mt-1 text-sm text-gray-500">Ingresá una palabra por línea, entre 4 y 14 letras, seguida de su pista.</p></div><ExampleButton onClick={() => { setTitle("Ciencias naturales"); setEntries("ÁRBOL: Planta de tronco leñoso.\nFLOR: Parte colorida de una planta.\nTIERRA: Capa superficial donde crecen las plantas."); }} /></div><label className="block text-sm font-medium text-gray-700">Título (opcional)<input value={title} onChange={(event) => setTitle(event.target.value)} className="input-field mt-1.5 w-full rounded-lg border border-gray-300 px-3.5 py-2.5 outline-none" placeholder="Ej: Ciencias naturales" /></label><label htmlFor="wordle-entries" className="block text-sm font-medium text-gray-700">Palabras y pistas<textarea id="wordle-entries" value={entries} onChange={(event) => setEntries(event.target.value)} rows={8} spellCheck={false} className="input-field mt-1.5 w-full resize-y rounded-lg border border-gray-300 px-3.5 py-2.5 font-mono text-sm outline-none" placeholder={"ÁRBOL: Planta de tronco leñoso.\nFLOR: Parte colorida de una planta."} /><span className="mt-1 block text-xs font-normal text-gray-500">Formato: <code>PALABRA: Pista</code>. La pista es opcional.</span></label><Button onClick={generate}>Generar juego</Button></section>;
}
